// Shared fetch-to-blob download helper. A plain <a download> only works for
// same-origin static assets — anything served from another origin (MinIO) or
// generated by an API response (this repo's pptx export) needs the browser to
// fetch the bytes into a Blob first, or the anchor just navigates instead of
// saving.
export async function downloadBlobFrom(url: string, filename: string, init?: RequestInit): Promise<void> {
  const res = await fetch(url, init)
  if (!res.ok) throw new Error(`Download failed (${res.status})`)
  const blobUrl = URL.createObjectURL(await res.blob())
  const a = document.createElement('a')
  a.href = blobUrl
  a.download = filename
  a.click()
  URL.revokeObjectURL(blobUrl)
}
